application: to-a-pe
version: 1
runtime: python
api_version: 1

handlers:
- url: /images
  static_dir: images
  
- url: /style
  static_dir: style

- url: /js
  static_dir: js
  
- url: /(.*\.(html|htm|txt|ico|xml))
  static_files: static/\1
  upload: static/(.*\.(html|htm|txt|ico|xml))
  
- url: /remote_api
  script: $PYTHON_LIB/google/appengine/ext/remote_api/handler.py
  login: admin
  
- url: .*
  script: main.py
