application: to-a-pe
version: 2
runtime: python
api_version: 1

handlers:
- url: /stats.*
  script: $PYTHON_LIB/google/appengine/ext/appstats/ui.py  

- url: /remote_api
  script: $PYTHON_LIB/google/appengine/ext/remote_api/handler.py
  login: admin

- url: /images
  static_dir: static/images
  
- url: /style
  static_dir: static/style

- url: /js
  static_dir: static/js
  
- url: /sitemap.txt
  script: main.py

- url: /(.*\.(html|htm|txt|ico|xml))
  static_files: static/\1
  upload: static/(.*\.(html|htm|txt|ico|xml))
    
- url: .*
  script: main.py